version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:2.1
    steps:
      - checkout
      - run:
          name: Install opam dependencies
          command: ./scripts/install-opam-deps
      - run:
          name: Build
          command: ./scripts/build
      - run:
          name: Test
          command: ./scripts/test
      - run:
          name: Install
          command: ./scripts/install
  semgrep:
    docker:
      - image: returntocorp/semgrep:develop
    steps:
      - checkout
      - run: unset SEMGREP_IN_DOCKER; semgrep -e 'Pervasives.$X' -l ocaml --error .
workflows:
  version: 2
  build_and_semgrep:
    jobs:
      - build
      - semgrep
