version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:2.1
    steps:
      - checkout
      - run: ./scripts/install-opam-deps
      - run: ./scripts/build
      - run: ./scripts/test
      - run: ./scripts/install
